name: vibingtownflutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.0.0
  flame_fire_atlas: ^1.0.0-rc1
  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  hovering: ^1.0.4
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pagebuttons.fa
    - assets/vibingtown.fa
  